=== InvictusInnovations/keyhotee/Wallets/Wallets.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           attributeFormDefault="unqualified" 
           elementFormDefault="qualified">
 
  <xs:element name="wallets">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="wallet">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="url" type="xs:string" />
              <xs:element name="icon" type="xs:string" />
              <xs:element name="server">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="arg" type="xs:string" minOccurs ="0" maxOccurs="unbounded" />
                  </xs:sequence>
                  <xs:attribute name="type" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="BitsharesClient"/>
                        <xs:enumeration value="other"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                  <xs:attribute name="path" type="xs:string" use="required" />
                  <xs:attribute name="port" type="xs:unsignedShort" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:decimal" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== InvictusInnovations/keyhotee/Wallets/DefaultWallets.xml
<?xml version="1.0" encoding="UTF-8"?>
<wallets version="1.0"
  xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.w3schools.com ./Wallets.xsd">
  
  <wallet name="Bitcoin">
    <url>http://www.bitcoin.com/</url>
    <!-- path to icon -->
    <icon>:images/bitcoin.png</icon>
    <!-- type: server enumeration type: BitsharesClient, other -->
    <server type="other" path="./plugins/bitshares_client.exe" port="80">
      <!-- optional command line arguments  -->
      <!-- <arg>command-line-arg1</arg>  -->
      <!-- <arg>command-line-arg2</arg>  -->
    </server>    
  </wallet>
  <wallet name="BitShares">
    <url>http://127.0.0.1/</url>
    <icon>:images/bitshares.png</icon>
    <server type="BitsharesClient" path="./plugins/bitshares_client.exe" port="9987">
		<arg>--data-dir</arg>
		<arg>$keyhotee_profile/BitSharesXT</arg>
	</server>
  </wallet>
  <wallet name="Litecoin">
    <url>https://litecoin.org/</url>
    <icon>:images/litecoin128.png</icon>
    <server type="other" path="./plugins/bitshares_client.exe" port="443"/>
  </wallet>
</wallets>
